### ISSUE TITLE
Streamlining between linux and windows

### ISSUE THREAD

**Issue by SteveTheMonkey12** [Sukhj1nder/ENGR101-Project-3#1]
I've had a look at both the Windows and Linux files and they are quite different, so I think the best course of action will be to just edit the cpp files for the robot for the time being, then fix up the compiling for one os at the end. Also probably best to raise issues and major changes proposed here to make sure we have a good log for report writing rather than hunting through discord messages

**Comment by Sukhj1nder** [comment]
Make a Install Section for the README.md and put instructions on how to install the program

**Comment by Sukhj1nder** [comment]
Fixed issue and made the README.md file better
